title: Brett Petch
description: Just a helpful student;<br> Web design, graphic design and photography are hobbies // Grade 12 @ BDHS.
show_downloads: false
google_analytics: UA-45906012-7
theme: jekyll-theme-cayman
